.Dd January 25, 2013
.Dt NetSniffer 1
.Os
.Sh NAME
.Nm netsniffer
.Nd Sniffer for network with arp spoofing
.Sh SYNOPSIS
.Nm netsniffer
.Sh DESCRIPTION
The
.Nm
utility is used ARP spoofing attack for change ARP tables on target attack host and on the gate.
.Sh FILES
.Bl -tag -width /usr/local/sbin/netsniffer -compact
.It Pa /usr/local/sbin/netsniffer
.El
.Sh SEE ALSO
.Xr tcpdump 1
.Sh AUTHORS
.An -nosplit
Source by
.An Stanislav Putrya Aq vagner@bsdway.ru
This
manual page was written by
.An Stanislav Putrya Aq vagner@bsdway.ru .
